app = "kinetic-rag"
primary_region = "iad"   # pick the closest region to your Supabase project

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  NODE_OPTIONS = "--dns-result-order=ipv4first"

# Two processes: API ("web") and background worker ("worker")
[processes]
  web = "node apps/rag-api/dist/server.js"
  worker = "node apps/rag-worker/dist/index.js"

# Network service for the web process only.
# The worker has no service because it doesn't listen on a port.
[[services]]
  processes = ["web"]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  # Public ports
  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    type = "requests"
    soft_limit = 50
    hard_limit = 100

  # Optional HTTP health check for the API
  [[services.http_checks]]
    path = "/healthz"
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
