openapi: 3.0.3
info:
  title: RAG Service API
  version: 1.0.0
servers: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: http
      scheme: bearer
security:
  - ApiKeyAuth: []
paths:
  /healthz:
    get:
      responses:
        "200":
          description: ok
